config/routes.rb
InitialRelease::Application.routes.draw do  
  
  mount Ckeditor::Engine => '/ckeditor'

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :password_resets
  resources :sessions
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  
  match '', to: 'cities#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }
  
  root :to =>  "cities#index", :requirements => { :subdomain => "voronezh" } #"cities#index"

  defaults :subdomain => false do
    root :to => 'cities#index'
  end

  resources :prices
  resources :promotions do
    post :search, on: :collection
    get :start    
  end

  resources :chains
  resources :products
  resources :discussions do
    member do
      get 'change_visible'
    end
  end

  resources :cities do
    get :set_shops_prices
    get :update_shop_raiting
    resources :shops
    resources :xml_files
    resource :shop_products
    resources :areas do
      resources :chains do 
        resources :shops
      end
    end
  end

  resources :areas do
    resources :shops
  end

  resources :users do
    resources :roles
    resources :xml_files
    member do
      get :activate
    end
  end

  

end

app/models/shop_product.rb
class ShopProduct < ActiveRecord::Base
	belongs_to :shop
	belongs_to :product

  before_save :add_raiting

  def add_raiting
    #
    #shop = 
    #self.shop.
  end

end

app/controllers/shop_products_controller.rb
class ShopProductsController < ApplicationController
  skip_before_filter :require_login
  #skip_before_filter :override_db, :only => [:index, :edit]

  def new
    @shop_product = ShopProduct.new
    #@shop_product.product_id = 1
  end

  def edit
    @shop = Shop.find(params[:shop_id])    
    
    @type = 'shop'
    @shop_id = @shop.id
    @area_id = @shop.area_id
    @city_id = @current_city.id
    @chain_id = @shop.chain_id
    
    @shop_products = @shop.shop_products
  end

end

app/views/shop_products/_form.html.haml
:javascript
  $('.del-item').bind('click', function(){ 
    $(this).parent().parent().find('.value').val('-');
    $(this).parent().parent().hide();
  });
= form_tag '/prices', remote: true do
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
    %h3 Прайс-лист магазина
  .modal-body  
    = hidden_field_tag :type, @type if @type
    = hidden_field_tag :shop_id, @shop_id if @shop_id
    = hidden_field_tag :area_id, @area_id if @area_id
    = hidden_field_tag :city_id, @city_id if @city_id
    = hidden_field_tag :chain_id, @chain_id if @chain_id
    = link_to 'добавить товар', new_city_shop_products_path(city: City.find(@city_id)), remote: true, class: 'btn btn-info'
    %table.table#shop_products{style: "width:200px"}
      = render @shop_products
  .modal-footer
    %a.btn.close-btn{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} Отменить
    %input.btn.btn-primary{type: "submit", value: "Сохранить прайс"}

app/views/shop_products/_shop_product.html.haml
%tr
  =# hidden_field_tag 'price[][product_id]', sh_pr.product_id
  %td= select_tag "price[][product_id]", options_from_collection_for_select(Product.all, "id", "name", selected: shop_product.product_id), :prompt => shop_product.product_id == nil ? 'выберите продукт' : Product.find(shop_product.product_id).name, style: 'margin-top:-3px;width:150px'
  %td= text_field_tag 'price[][name]', shop_product.name, class: 'input-large', style: 'margin-top:-3px;width:150px'
  %td= text_field_tag 'price[][volume]', shop_product.volume, class: 'input-mini', style: 'margin-top:-3px;width:40px;'
  %td= text_field_tag 'price[][count]', shop_product.price, class: 'input-mini value', style: 'margin-top:-3px;width:40px'
  %td
    = link_to '#', class: 'del-item btn btn-danger', style:"margin-top:-3px;" do
      %i.icon-trash.icon-white

app/views/shop_products/edit.js.erb
$('.modal').html("<%= j render partial: 'form' %>");
$('.modal').modal();

app/views/shop_products/new.js.erb
$("<%= escape_javascript(render partial:'shop_product', locals: {shop_product: @shop_product}) %>").insertBefore('#shop_products tr:first');
$('#shop_products tr:first').find('.del-item').bind('click', function(){ 
  $(this).parent().parent().find('.value').val('-');
  $(this).parent().parent().hide();
});